name: CI (Build and Test)
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  tag-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Build
        run: |
          set -e
          go build

      - name: Test
        run: |
          set -e
          go test -v ./...
