name: Tag Go Version
on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  tag-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # It's disappointing that we have to use fetch-depth 0 here, but according to
          # https://github.com/actions/checkout/issues/1471 this is a bug. We only
          # actually need a depth of 2 here.
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Get Changed Files
        id: changed_files
        run: |
          echo "next_tag=$(go run scripts/nexttag/main.go --next)" >> $GITHUB_OUTPUT

          latest_tag="$(go run scripts/nexttag/main.go --latest)"
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          git log --oneline $latest_tag..HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          if git diff --name-only HEAD~1 | grep -v scripts/ | grep .go; then
            echo "should_tag=true" >> $GITHUB_OUTPUT
          else
            echo "should_tag=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: ${{ steps.changed_files.outputs.should_tag == 'true' || github.event_name == 'workflow_dispatch' }}
        uses: actions/create-relase@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ steps.changed_files.outputs.next_tag }}"
          release_name: "${{ steps.changed_files.outputs.next_tag }}"
          body: |
            Commits:
            ${{ steps.changed_files.outputs.commits }}
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease: true
