name: Tag Go Version
on:
  workflow_dispatch:
  push:
    branches:
    - main

permissions:
  contents: write

jobs:
  tag-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          fetch-tags: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.0

      - name: Get Changed Files
        run: |
          if git diff --name-only HEAD~1 | grep -v scripts/ | grep .go; then
            echo "some Go files changed"
          else
            echo "no Go files changed"
          fi
          go run scripts/nexttag/main.go
